### ISSUE TITLE
Generated IDL files are missing

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/segmentation#2] opened 2016-01-07 18:07 UTC
Hi @pattacini,

it seems the generated IDL files didn't make it in the new repository.

Error as follows:
```
icub@icuboracle:~/robot/segmentation/build$ make
-- Installation prefix is different from YARP: no file will we be installed into path.d folder, you need to set YARP_DATA_DIRS environment variable to /usr/local/src/robot/install/wysiwyd/share/wysiwyd:/usr/local/src/robot/install/icub-main/share/iCub:/usr/local/src/robot/install/ICUBcontrib/share/ICUBcontrib:/usr/local/src/robot/install/yarp/share/yarp:/usr/local/src/robot/install/ICUBcontrib/share/ICUBcontrib
-- Installation prefix is different from YARP: no file will we be installed into path.d folder, you need to set YARP_DATA_DIRS environment variable to /usr/local/src/robot/install/wysiwyd/share/wysiwyd:/usr/local/src/robot/install/icub-main/share/iCub:/usr/local/src/robot/install/ICUBcontrib/share/ICUBcontrib:/usr/local/src/robot/install/yarp/share/yarp:/usr/local/src/robot/install/ICUBcontrib/share/ICUBcontrib
-- Not processing thrift file EDISONsegmentation.thrift, ALLOW_IDL_GENERATION=OFF
-- Installation prefix is different from YARP: no file will we be installed into path.d folder, you need to set YARP_DATA_DIRS environment variable to /usr/local/src/robot/install/wysiwyd/share/wysiwyd:/usr/local/src/robot/install/icub-main/share/iCub:/usr/local/src/robot/install/ICUBcontrib/share/ICUBcontrib:/usr/local/src/robot/install/yarp/share/yarp:/usr/local/src/robot/install/ICUBcontrib/share/ICUBcontrib
-- Libraries are placed in /home/icub/robot/segmentation/build/lib
-- Executables are placed in /home/icub/robot/segmentation/build/bin
CMake Error at /usr/local/src/robot/install/yarp/share/yarp/cmake/YarpIDL.cmake:155 (message):
  Generated IDL files for
  iCub/segmentation/graphBasedSegmentationInterface.thrift not found and
  cannot make them because ALLOW_IDL_GENERATION=OFF (maybe this should be
  turned on?)
Call Stack (most recent call first):
  graphBased/thriftGBseg/CMakeLists.txt:7 (yarp_idl_to_dir)


-- Configuring incomplete, errors occurred!
See also "/home/icub/robot/segmentation/build/CMakeFiles/CMakeOutput.log".
make: *** [cmake_check_build_system] Error 1
```

Best,
Tobi

**Comment by pattacini** [comment] 2016-01-07 23:09
I'm afraid that the latest changes to yarp concerned with IDL were a bit ... disruptive.

This chunk of code was no longer configurable via IDL: I made therefore an attempt to streamline the automatic generation of files, removing nested structure of sub-directories.

Moreover, I've seen several time that we need to include `yarp/os/Value.h` here and there even if we do not refer to `Value` in the code at all. There must be something weird also in this respect (see e.g. https://github.com/robotology/iol/commit/d082d86df3becfe3425effcbc923eafdc34dc02d).

@drdanz could you have a look at this?

**Comment by pattacini** [comment] 2016-01-07 23:15
I think `yarp/os/Bottle.h` should include `yarp/os/Value.h`, since it makes use of `Value` inside.

**Comment by drdanz** [comment] 2016-01-08 07:58
@pattacini `yarp/os/Bottle.h` should not include `yarp/os/Value.h`, it does not need it in the header file. The `yarp::os::Bottle::get()` method (and a few others) returns a reference to a `yarp::os::Value`, you don't need to include `yarp/os/Value.h` to do that, because the compiler knows the size of a reference, for example this compiles:

```c++
#include <yarp/os/Bottle.h>

int main(int argc, char *argv[])
{
    yarp::os::Bottle b;
    b.addInt(10);
    yarp::os::Value& v = b.get(0);

    return 0;
}
```

On the other hand, when you call methods on `yarp::os::Value` the compiler needs to know about the members of the class, therefore you need to include `yarp/os/Value.h`, for example this will not compile if you remove the include:

```c++
#include <yarp/os/Bottle.h>
#include <yarp/os/Value.h>

int main(int argc, char *argv[])
{
    yarp::os::Bottle b;
    b.addInt(10);
    yarp::os::Value& v = b.get(0);
    int i = v.asInt();

    return 0;
}
```

For the same reason, this will not compile if you remove the include:

```c++
#include <yarp/os/Bottle.h>
#include <yarp/os/Value.h>

int main(int argc, char *argv[])
{
    yarp::os::Bottle b;
    b.addInt(10);
    int i = b.get(0).asInt();

    return 0;
}
```

In the last example, you don't notice that you are using a `yarp::os::Value`, but you actually are.

**Comment by pattacini** [comment] 2016-01-08 08:08
I might be wrong, but the module [`classifierHandling`](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp) in `iol` does not compile without the inclusion of `yarp/os/Value.h`, even though it does not use `Value` at all. It only includes `yarp/os/Bottle.h` within its own header.

If so, I think it is very confusing.

**Comment by pattacini** [comment] 2016-01-08 08:11
I got the point but I still think it's quite subtle and tricky not to include `yarp/os/Value.h` in Bottle header ...

**Comment by pattacini** [comment] 2016-01-08 08:13
... also considering that it's causing compilation errors in many parts :smirk:

**Comment by drdanz** [comment] 2016-01-08 08:27
I count at least 18 places in `classifierHandling.cpp` where `yarp::os::Value` is being used:

* [L181](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L181): `options.find("name").asString()` -> `yarp::Value::asString()`
* [L184](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L184): `options.find("threshold").asDouble()` -> `yarp::Value::asDouble()`
* [L187](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L187): `options.find("winLen").asInt()` -> `yarp::Value::asInt()`
* [L189](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L189): `options.find("items").asList()` -> `yarp::Value::asList()`
* [L194](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L194): `item_list->get(i).asString()` -> `yarp::Value::asString()`
* [L195](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L195): `item_list->get(i+1).asDouble()` -> `yarp::Value::asDouble()`
* [L279](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L279): `scores.find(tag.str().c_str()).asList()` -> `yarp::Value::asList()`
* [L285](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L285): `blobScores->get(j).asList()` -> `yarp::Value::asList()`
* [L289](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L289): `item->get(0).asString()` -> `yarp::Value::asString()`
* [L290](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L290): `item->get(1).asDouble()` -> `yarp::Value::asDouble()`
* [L318](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L318): `scores.find(tag.c_str()).asList()` -> `yarp::Value::asList()`
* [L325](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L325): `blobScores->get(i).asList()` -> `yarp::Value::asList()`
* [L329](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L329): `item->get(0).asString()` -> `yarp::Value::asString()`
* [L330](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L330): `item->get(1).asDouble()` -> `yarp::Value::asDouble()`
* [L349](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L349): `scores.get(i).asList()` -> `yarp::Value::asList()`
* [L352](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L352): `blob->get(0).asString()` -> `yarp::Value::asString()`
* [L353](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L353): `blob->get(1).asList()` -> `yarp::Value::asList()`
* [L357](https://github.com/robotology/iol/blob/master/src/iolStateMachineHandler/src/classifierHandling.cpp#L357): `blobScores->find(retName.c_str()).asDouble()` -> `yarp::Value::asDouble()`

**Comment by pattacini** [comment] 2016-01-08 08:34
As said, I got the point: the use therein is implicit and doesn't go through an explicit reference to a `Value` object. But still, for the exact same reason, my personal opinion is that we have a subtle behavior here.

A "puristic" solution in the end has caused a bit of hassle in yarp-dependent code.

**Comment by drdanz** [comment] 2016-01-08 09:38
It's not a puristic solution, that's how library normally works. Forward declarations mean faster build times, and therefore happier developers! :smirk:

Also, perhaps it is not such a common case, but the `Bottle` class used to work in the same way if you "implicitly" used `yarp::os::Property`, i.e. this will not compile without `yarp/os/Property.h`

```c++
#include <yarp/os/Bottle.h>
#include <yarp/os/Property.h>

int main(int argc, char *argv[])
{
    yarp::os::Bottle b;
    b.addDict().put("foo", "bar");
    return 0;
}
```

Anyway, if this is a big deal, we can go back and include the file... @lornat75 what do you think?

**Comment by pattacini** [comment] 2016-01-08 09:48
I don't like **forward declaration** indeed :smile: and I happen to use it only when strictly needed. I'm also for fixing/restyling downstream projects only when strictly needed :smirk:.

I was just concerned because I've seen a bunch of `Value`-related compilation problems showing up without knowing why.

**Comment by lornat75** [comment] 2016-01-08 10:09
I think forward declarations should be used whenever possible, but if Value.h used to be included and now removing it creates a lot of problems then maybe we can make an exception.

**Comment by Tobias-Fischer** [comment] 2016-01-08 10:15
The actual issue is resolved, so please feel free to close here as soon as there is an agreement on the forward declaration issue ..

**Comment by pattacini** [comment] 2016-01-08 11:27
I found this sugegstion from Google style: https://google.github.io/styleguide/cppguide.html#Forward_Declarations.
It can be pertinent too.

**Comment by drdanz** [comment] 2016-01-08 12:59
@pattacini about the IDL issue, the problem is that for some reason that I still have to understand I somehow changed the paths for the generated files when there are sub-directories.

The unit tests could not spot this as they generate the files in the binary directory using `ALLOW_IDL_GENERATION=ON` all the time.

from `iCub/segmentation/graphBasedSegmentationInterface.thrift`

* `include/iCub/segmentation/Pixel.h` (unchanged)
* `include/iCub/segmentation/SegmentationModuleInterface.h` (unchanged)
* `iCub_segmentation_graphBasedSegmentationInterface_thrift.cmake` -> ~~`graphBasedSegmentationInterface_thrift.cmake`~~ (**and there is an error inside**)
* ~~`src/iCub/segmentation/Pixel.cpp`~~ -> `src/Pixel.cpp`
* ~~`src/iCub/segmentation/SegmentationModuleInterface.cpp`~~ ->`src/SegmentationModuleInterface.cpp`

I think that the new names for the c++ files make more sense, therefore I kept the new names, but I just changed back the cmake file name and fixed its content, as that's what was causing this issue. The files not stroked are the ones that I left.

Nonetheless when you re-generate the IDL files you will have to remove the old committed cpp and add the new one. I'm inclined to believe that nested paths are not used anywhere else, therefore I think this should not be an issue.

**Comment by pattacini** [comment] 2016-01-08 13:13
@drdanz I agree with you for what concerns the place of `*.cpp` files and I also believe this was the only example with such nested branching.

I'd rather keep the new structure of `thriftGBseg`: it's simpler and cleaner.

Thanks a lot for the fix.
I think we can close this issue.

**Closed** 2016-01-08 14:50 UTC

**Comment by lornat75** [comment] 2016-01-11 09:46
Thanks for the link @pattacini. I think you have a good point in saying that in this case the forward declaration makes the use of Bottle and Value quite tricky. 

Maybe a reasonable approach could be to use forward declarations only for types that are not exposed by the object interface (as it is in this case for Property and Value). 

If you think it is important, we can move this discussion to YARP.

**Comment by pattacini** [comment] 2016-01-11 09:56
Yep, I think the approach you're suggesting will help keep API clear with the only downside of a slightly lower compilation speed.

It's not necessary for me to discuss it further in a dedicated ticket.
